const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const path=require('node:path');
const elements=new Map();
const node=id=>{if(!elements.has(id))elements.set(id,{textContent:'',innerHTML:'',classList:{toggle(){}},setAttribute(){}});return elements.get(id);};
const context={document:{getElementById:node},window:{},localStorage:{getItem:()=>null,setItem(){}},Date,Intl,Math,JSON,String,Array,Set,Map,console,module:{exports:{}}};
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../android/app/src/main/assets/game.js'),'utf8'),context);
const {pathPuzzle,sumPuzzle,memoryPuzzle,neighbors,swapDistance,solvedCount}=context.module.exports;
for(let seed=0;seed<300;seed++)for(let level=1;level<=12;level++){
  const p=pathPuzzle(seed,level);
  assert.equal(new Set(p.route).size,p.route.length);
  assert.equal(p.anchors.get(p.route[0]),1);
  assert.equal(p.anchors.get(p.route[p.route.length-1]),p.anchors.size);
  assert.equal(p.route.length+p.walls.size,p.n*p.n);
  assert.equal(p.n,level<3?4:level<7?5:6);
  p.route.forEach((cell,i)=>{assert.ok(cell>=0&&cell<p.n*p.n);assert.ok(!p.walls.has(cell));if(i)assert.ok(neighbors(cell,p.n).includes(p.route[i-1]));});
  const s=sumPuzzle(seed,level);
  assert.equal(new Set(s.tiles).size,9);
  assert.equal(s.rows.reduce((a,b)=>a+b),45);
  assert.equal(s.cols.reduce((a,b)=>a+b),45);
  assert.equal(swapDistance(s.tiles,s.solution),s.par);
  assert.ok(s.par>=2&&s.par<=6);
  assert.ok(solvedCount(s)<6);
  const first=s.tiles.findIndex((v,i)=>v!==s.solution[i]),partner=s.tiles.indexOf(s.solution[first]);
  assert.ok(first!==partner&&first>=0&&partner>=0);
  s.tiles=s.solution.slice();
  assert.equal(solvedCount(s),6);
  const m=memoryPuzzle(seed,level);
  assert.ok(m.sequence.length>=3&&m.sequence.every(i=>i>=0&&i<m.n*m.n));
  assert.ok(m.sequence.every((i,j)=>j===0||i!==m.sequence[j-1]));
  assert.equal(m.reverse,level>=6);
}
console.log('3,600 seeds × 3 puzzle types: valid and solvable');
